# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "wagmi", to: "https://ga.jspm.io/npm:wagmi@1.2.0/dist/index.js"
pin "@adraffy/ens-normalize", to: "https://ga.jspm.io/npm:@adraffy/ens-normalize@1.9.0/dist/index.js"
pin "@noble/curves/abstract/utils", to: "https://ga.jspm.io/npm:@noble/curves@1.0.0/esm/abstract/utils.js"
pin "@noble/curves/secp256k1", to: "https://ga.jspm.io/npm:@noble/curves@1.0.0/esm/secp256k1.js"
pin "@noble/hashes/crypto", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.0/esm/crypto.js"
pin "@noble/hashes/hmac", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.0/esm/hmac.js"
pin "@noble/hashes/sha256", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.0/esm/sha256.js"
pin "@noble/hashes/sha3", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.0/esm/sha3.js"
pin "@noble/hashes/utils", to: "https://ga.jspm.io/npm:@noble/hashes@1.3.0/esm/utils.js"
pin "@tanstack/query-core", to: "https://ga.jspm.io/npm:@tanstack/query-core@4.29.14/build/lib/index.mjs"
pin "@tanstack/query-persist-client-core", to: "https://ga.jspm.io/npm:@tanstack/query-persist-client-core@4.29.14/build/lib/index.mjs"
pin "@tanstack/query-sync-storage-persister", to: "https://ga.jspm.io/npm:@tanstack/query-sync-storage-persister@4.29.19/build/lib/index.mjs"
pin "@tanstack/react-query", to: "https://ga.jspm.io/npm:@tanstack/react-query@4.29.14/build/lib/index.mjs"
pin "@tanstack/react-query-persist-client", to: "https://ga.jspm.io/npm:@tanstack/react-query-persist-client@4.29.14/build/lib/index.mjs"
pin "@wagmi/chains", to: "https://ga.jspm.io/npm:@wagmi/chains@1.1.0/dist/index.mjs"
pin "@wagmi/connectors", to: "https://ga.jspm.io/npm:@wagmi/connectors@2.2.0/dist/index.js"
pin "@wagmi/connectors/injected", to: "https://ga.jspm.io/npm:@wagmi/connectors@2.2.0/dist/injected.js"
pin "@wagmi/core", to: "https://ga.jspm.io/npm:@wagmi/core@1.2.0/dist/index.js"
pin "@wagmi/core/internal", to: "https://ga.jspm.io/npm:@wagmi/core@1.2.0/dist/internal/index.js"
pin "abitype", to: "https://ga.jspm.io/npm:abitype@0.8.7/dist/esm/index.js"
pin "eventemitter3", to: "https://ga.jspm.io/npm:eventemitter3@4.0.7/index.js"
pin "isomorphic-ws", to: "https://ga.jspm.io/npm:isomorphic-ws@5.0.0/browser.js"
pin "react", to: "https://ga.jspm.io/npm:react@18.2.0/index.js"
pin "react-dom", to: "https://ga.jspm.io/npm:react-dom@18.2.0/index.js"
pin "scheduler", to: "https://ga.jspm.io/npm:scheduler@0.23.0/index.js"
pin "use-sync-external-store/shim", to: "https://ga.jspm.io/npm:use-sync-external-store@1.2.0/shim/index.js"
pin "use-sync-external-store/shim/", to: "https://ga.jspm.io/npm:use-sync-external-store@1.2.0/shim/"
pin "viem", to: "https://ga.jspm.io/npm:viem@1.0.7/dist/esm/index.js"
pin "viem/chains", to: "https://ga.jspm.io/npm:viem@1.0.7/dist/esm/chains.js"
pin "viem/ens", to: "https://ga.jspm.io/npm:viem@1.0.7/dist/esm/ens.js"
pin "zustand/middleware", to: "https://ga.jspm.io/npm:zustand@4.3.8/esm/middleware.mjs"
pin "zustand/shallow", to: "https://ga.jspm.io/npm:zustand@4.3.8/esm/shallow.mjs"
pin "zustand/vanilla", to: "https://ga.jspm.io/npm:zustand@4.3.8/esm/vanilla.mjs"
pin "@wagmi/core/providers/public", to: "https://ga.jspm.io/npm:@wagmi/core@1.2.0/dist/providers/public.js"
pin "@wagmi/core/connectors/injected", to: "https://ga.jspm.io/npm:@wagmi/core@1.2.0/dist/connectors/injected.js"
